baseURL = 'https://terminalninja.github.io/arun.fitness/'
languageCode = 'en-us'
title = 'Ashan the great'
theme = 'papermod'

[params.profileMode]
enabled = true
title = "Ashan"
subtitle = "All hail Ashaan"

  [[params.profileMode.buttons]]
  name = "Archive"
  url = "/archive"
