baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'papermod'

[params.profileMode]
enabled = true
title = "Test"
subtitle = "This is subtitle"

  [[params.profileMode.buttons]]
  name = "Archive"
  url = "/archive"

  [[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/"
